### PR TITLE
Add pod spec

### PR DESCRIPTION
**Pull request by gsabran**

### CODE REVIEW

**Comment by lukaskubanek** [comment]
Hi @gsabran, thanks for this contribution. However I don't want to support CocoaPods myself. See #7 for the explanation.

**Comment by gsabran** [comment]
And are you ok with someone else (me?) publishing to cocoapod your repo and keeping it up to date?

**Comment by lukaskubanek** [comment]
@gsabran: I'd prefer if you could use this podspec file internally in your projects. As far as I can remember there should be an option to use local podspecs in CocoaPods.

**Comment by gsabran** [comment]
Yes, but it's quite annoying to have local repos in projects since they have to be tracked by the version control while usually my podfile is enough to describe all this pod code. There's no need to publish to cocoapods if the github repo has a podfile itself. So I had to fork your repo to be able to include it in my project with just

    pod 'SDAVAssetExportSession', :git => 'https://github.com/gsabran/SDAVAssetExportSession.git', :tag => '0.0.3'

and I thought a few other people will have to fork it as well to do just that.

**Comment by lukaskubanek** [comment]
You don't have to fork the whole repository. All you need to do (as far as I understand CocoaPods) is to host the podspec file somewhere. See the last section of [this post](https://guides.cocoapods.org/syntax/podfile.html#pod). I'm not sure whether it has to be online or whether it can be local in your project. I think the latter option should also work.

**Comment by gsabran** [comment]
Ah true, I didn't know that. Thanks!

**Pull request closed without merging**
